resolver: ghc-8.10.2
compiler: ghc-8.10.2
compiler-check: match-exact

extra-deps:
# For BNFC, package 'source'
- alex-3.2.5
- happy-1.19.12
- semigroups-0.19.1
- string-qq-0.0.4

# For --test and package 'testing'
- Diff-0.4.0
- HTF-0.14.0.6
- HUnit-1.6.0.0
- QuickCheck-2.13.2
- aeson-1.5.3.0
- ansi-terminal-0.11
- assoc-1.0.2
- async-2.2.2
- attoparsec-0.13.2.4
- base-compat-0.11.1
- base-compat-batteries-0.11.1
- base-orphans-0.8.2
- base64-bytestring-1.2.0.0
- bifunctors-5.5.7
- blaze-builder-0.4.1.0
- cabal-doctest-1.0.8
- call-stack-0.2.0
- clock-0.8
- code-page-0.2
- colour-2.3.5
- comonad-5.0.6
- constraints-0.12
- cpphs-1.20.9.1
- data-fix-0.3.0
- distributive-0.6.2
- dlist-0.8.0.8
- doctest-0.17
- enclosed-exceptions-1.0.3
- ghc-paths-0.1.0.12
- hashable-1.3.0.0
- haskell-src-1.0.3.1
- hspec-2.7.4
- hspec-core-2.7.4
- hspec-discover-2.7.4
- hspec-expectations-0.8.2
- integer-logarithms-1.0.3
- lifted-async-0.10.1.2
- lifted-base-0.2.3.12
- monad-control-1.0.2.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- polyparse-1.13
- primitive-0.7.1.0
- quickcheck-io-0.2.0
- random-1.1
# - random-1.2.0 # dependency cycle, and HTF does not like it
- regex-base-0.94.0.0
- regex-compat-0.95.2.0
- regex-posix-0.96.0.0
- scientific-0.3.6.2
- setenv-0.1.1.3
- shelly-1.9.0
- splitmix-0.0.5
- strict-0.4
- syb-0.7.1
- tagged-0.8.6
- temporary-1.3
- tf-random-0.5
- th-abstraction-0.3.2.0
- these-1.1.1.1
- time-compat-1.9.3
- transformers-base-0.4.5.2
- transformers-compat-0.6.5
- type-equality-1
- unix-compat-0.5.2
- unordered-containers-0.2.12.0
- uuid-types-1.0.3
- vector-0.12.1.2
- xmlgen-0.6.2.2

# NOT NEEDED
# - ListLike-4.7.1
# - STMonadTrans-0.4.4
# - ansi-terminal-0.10.3
# - ansi-wl-pprint-0.6.9
# - blaze-html-0.9.1.2
# - blaze-markup-0.8.2.7
# - boxes-0.1.5
# - case-insensitive-1.2.1.0
# - clock-0.8
# - cmdargs-0.10.20
# - colour-2.3.5
# - conduit-1.3.2
# - data-default-0.7.1.1
# - data-default-class-0.1.2.0
# - data-default-instances-containers-0.0.1
# - data-default-instances-dlist-0.0.1
# - data-default-instances-old-locale-0.0.1
# - data-hash-0.2.0.1
# - edit-distance-0.2.2.1
# - equivalence-0.3.5
# - extensible-exceptions-0.1.1.4
# - extra-1.7.2
# - fail-4.9.0.0
# - filemanip-0.3.6.3
# - filepattern-0.1.2
# - fmlist-0.9.3
# - generic-deriving-1.13.1
# - gitrev-1.3.1
# - hashtables-1.2.3.4
# - haskell-lexer-1.1
# - hostname-1.0
# - ieee754-0.8.0
# - libyaml-0.1.2
# - mono-traversable-1.0.15.1
# - murmur-hash-0.1.0.9
# - network-uri-2.6.3.0
# - optparse-applicative-0.16.0.0
# - pretty-show-1.10
# - process-extras-0.7.4
# - regex-tdfa-1.3.1.0
# - resourcet-1.2.3
# - safe-0.3.19
# - split-0.2.3.4
# - tasty-1.2.3
# - tasty-hunit-0.10.0.2
# - tasty-quickcheck-0.10.1.1
# - tasty-silver-3.1.15
# - temporary-1.3
# - test-framework-0.8.2.0
# - test-framework-hunit-0.3.0.2
# - text-icu-0.7.0.1
# - unbounded-delays-0.1.1.0
# - unliftio-core-0.2.0.1
# - uri-encode-1.5.0.6
# - utf8-string-1.0.1.1
# - vector-algorithms-0.8.0.3
# - wcwidth-0.0.2
# - xml-1.3.14
# - yaml-0.11.3.0
# - zlib-0.6.2.2

flags:
  transformers-compat:
    five-three: true

# Local packages, usually specified by relative directory name
packages:
- 'source'
- 'testing'
